idf_component_register(SRCS "main.c" 
                              "wifi_sta.c" 
                              "mqtt_tools.c"
                              "fsm.c" 
                              "pid_controller.c" 
                              "lut_calibration.c"
                              "dac_control.c" 
                              "mcpwm_capture.c" 
                              "udp_telemetry.c"
                       INCLUDE_DIRS "."
                       REQUIRES esp_wifi esp_event esp_netif mqtt driver nvs_flash freertos)